<a href="https://colab.research.google.com/github/Jagoda222/HCML_2/blob/main/ID_Jaco.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intersectional Divergence try 1
This is to see whether we can use the code provided by the researchers that produced the paper on Intersectional Divergence (ID).

In [3]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

In [6]:
# !pip install iron
from iron import phi

ImportError: cannot import name 'phi' from 'iron' (/usr/local/lib/python3.11/dist-packages/iron/__init__.py)

### Data

In [9]:
# load data
data = pd.read_csv("adult_reconstruction.csv")
print("Data loaded")

Data loaded


In [10]:
print(data.head())

   hours-per-week  age  capital-gain  capital-loss workclass     education  \
0              20   40             0             0   Private     Bachelors   
1              40   21             0             0   Private  Some-college   
2              10   17             0             0   Private          11th   
3              50   51             0             0   Private       HS-grad   
4              38   28             0             0   Private     Bachelors   

   education-num      marital-status   relationship                race  \
0             13  Married-civ-spouse           Wife               White   
1             10            Divorced      Own-child               White   
2              7       Never-married      Own-child               White   
3              9  Married-civ-spouse        Husband  Asian-Pac-Islander   
4             13       Never-married  Not-in-family               White   

   gender native-country  income       occupation  
0  Female  United-States   4

In [11]:
# checking for missing values
# for col in data:
#     print(col)
#     print(data[col].unique()) # native-country and occupation contain '?'

# print(data['native-country'].value_counts()) # 859 question marks
# print(data['occupation'].value_counts()) # 2869 question marks

before = len(data)
print(before)

# drop all rows with '?' at either native-country or occupation
data = data.drop(data[data['native-country'] == '?'].index)
data = data.drop(data[data['occupation'] == '?'].index)

print(len(data))
print("So dropped values are:", before-len(data))

49531
45849
So dropped values are: 3682


### Getting the ID loss function

> Add blockquote



### Simple regression model on data

In [12]:
# split data with 80-20 train-testsplit
# X = data.drop(columns=['income'])
# y = data['income']
# print(y)

# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.2, random_state=42
# )
cat_features = ['workclass', 'education', 'marital-status', 'relationship', 'race', 'gender', 'native-country', 'occupation']

encoded_df = data.copy()  # Use .copy() to avoid the warning
label_encoder = LabelEncoder()

for i in cat_features:
    encoded_df.loc[:, i] = label_encoder.fit_transform(encoded_df[i])
# print(encoded_df.head())

features = list(encoded_df.columns)
features.remove('income')

train_set, test_set = train_test_split(encoded_df, test_size=0.2)

X_train = np.array(train_set[features])
y_train = np.array(train_set['income'])

X_test = np.array(test_set[features])
y_test = np.array(test_set['income'])

print(X_train)

print(y_train)

[[40 57 0 ... 1 38 2]
 [40 48 0 ... 0 38 3]
 [50 31 0 ... 1 38 13]
 ...
 [35 65 6514 ... 1 38 9]
 [40 35 0 ... 0 38 5]
 [50 50 0 ... 1 38 2]]
[16878 57283 23009 ... 63140 19000 62028]


#### Linear

In [13]:
mod = LinearRegression().fit(X_train, y_train)
y_pred = mod.predict(X_test)

#### XGBoost

## ID metric

In [14]:
from ID import id
# id(trues: pd.Series, preds: pd.Series, X: pd.DataFrame, prot_attrs: list, pl: bool=False, return_errs: bool = False, ph=None, phi_trues=None):
print(id(y_test, y_pred, encoded_df, ['rece, gender, native_country']))

ImportError: cannot import name 'phi' from 'iron' (/usr/local/lib/python3.11/dist-packages/iron/__init__.py)